name: Run Gradle check

on:
  push:
    branches:
      - main
      - releases/*
  pull_request:

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2.5.0
      with:
        distribution: 'temurin'
        java-version: '8'
    - uses: kiancross/checkstyle-annotations-action@v1
    - uses: gradle/gradle-build-action@v2
      name: gradle check
      with:
        arguments: check
